export const BUTTON_PRESS = {
  START_GAME: 'START_GAME',
  START_DIFFICULTY: 'START_DIFFICULTY',
  START_LEVEL: 'START_LEVEL',
  DIFFICULTY_HIGHSCORE: 'DIFFICULTY_HIGHSCORE',
  BACK: 'BACK',
  DIFFICULTY_SUCCESS: 'DIFFICULTY_SUCCESS',
  HOME: 'HOME',
  HELP: 'HELP',
  START_DIFFICULTY: 'START_DIFFICULTY',
  RESTART_LEVEL: 'RESTART_LEVEL',
};

export const SETTINGS = {
  BRIGHTNESS_CHANGED: 'BRIGHTNESS_CHANGED', 
  };

export const  APP = {
    FIREBASE_AUTH_STATE_CHANGE: 'FIREBASE_AUTH_STATE_CHANGE',
  };

export const GAME = {
  LEVEL_SUCCESS: 'LEVEL_SUCCESS',
}

export const AUTH = {
  LOGIN_ANONYMOUSLY: 'LOGIN_ANONYMOUSLY',
}

export const ROUTER = {
  ROUTE_CHANGED: 'ROUTE_CHANGED',
}

export const ADS = {
  FINISHED: 'FINISHED',
}

export default {
  BUTTON_PRESS,
  SETTINGS,
  APP,
  GAME,
  AUTH,
  ROUTER,
  ADS,
};